### ISSUE TITLE
Criar endpoint '/courses'

### ISSUE THREAD

**Issue by brMonteiro-G** [ufabc-next/ufabc-next-ms-users#16]

**Comment by brMonteiro-G** [comment]
Para iniciarmos podemos criar um endpoint que devolva esses dados mockados, seria interessante conversar com o @Joabesv para enteder a estrutura a seguir para criar uma rota com node. Para saber os dados a serem devolvidos é interessante observar o mapeamento de api no Miro do ufabc-next

**Comment by Joabesv** [comment]
Will Close as stale, reopen once it gets more in the roadmap
